apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-petclinic
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/springboot-petclinic:latest
        ports:
        - containerPort: 8080
